# Generated by Django 5.2.15 on 2026-06-15 10:02

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('generated_title', models.CharField(blank=True, default='', max_length=255)),
                ('generated_description', models.TextField(blank=True, default='')),
                ('generated_hashtags', models.TextField(blank=True, default='')),
                ('ai_model_used', models.CharField(blank=True, default='', max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('access_token', core.fields.EncryptedTextField(blank=True, default='')),
                ('refresh_token', core.fields.EncryptedTextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('platform_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=500)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_caption', models.TextField(blank=True, default='')),
                ('scheduled_time_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('published', 'Published'), ('failed', 'Failed'), ('needs_reconnect', 'Needs reconnect')], default='pending', max_length=20)),
                ('platform_post_id', models.CharField(blank=True, default='', max_length=255)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_posts', to='core.aicontent')),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='core.socialaccount')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='core.video')),
            ],
            options={
                'ordering': ['scheduled_time_utc'],
            },
        ),
        migrations.AddField(
            model_name='aicontent',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_contents', to='core.video'),
        ),
        migrations.AddConstraint(
            model_name='socialaccount',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='unique_user_platform'),
        ),
        migrations.AddIndex(
            model_name='scheduledpost',
            index=models.Index(fields=['status', 'scheduled_time_utc'], name='core_schedu_status_1aec34_idx'),
        ),
    ]
