# Generated by Django 5.2.15 on 2026-06-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
