# Generated by Django 5.2.15 on 2026-06-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_video_cloudinary_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicontent',
            name='generation_status',
            field=models.CharField(choices=[('pending', 'Generating'), ('done', 'Ready'), ('failed', 'Failed')], default='done', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='user_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='user_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
