# Generated by Django 5.2.15 on 2026-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aicontent_generation_status_video_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private')], default='public', max_length=10),
        ),
    ]
