# Generated by Django 5.2.15 on 2026-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_scheduledpost_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('image', 'Image')], default='video', max_length=10),
        ),
    ]
