# Generated by Django 5.2.15 on 2026-06-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_video_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_public_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
