# Generated by Django 5.2.15 on 2026-06-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_video_source_deleted_video_thumbnail_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
