# Generated by Django 5.2.15 on 2026-06-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('expired', 'Expired'), ('needs_reconnect', 'Needs reconnect')], default='connected', max_length=20),
        ),
    ]
