# Generated by Django 5.2.15 on 2026-06-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_socialaccount_last_reminder_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='stat_comments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='stat_likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='stat_views',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='stats_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
