# Generated by Django 5.2.15 on 2026-06-21 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_video_source_size_bytes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stat_snapshots', to='core.scheduledpost')),
            ],
            options={
                'ordering': ['captured_at'],
                'indexes': [models.Index(fields=['post', 'captured_at'], name='core_statsn_post_id_b24616_idx')],
            },
        ),
    ]
