# Generated by Django 5.2.15 on 2026-07-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_statsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ai_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_media_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='video',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
