# Generated by Django 5.2.15 on 2026-07-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_video_ai_analysis_status_video_ai_media_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='r2_object_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
